### ISSUE TITLE
Update versions.py to match Socorro's versioning scheme

### ISSUE THREAD

**Issue by stephendonner** [mozilla/Socorro-Tests#270]
Please fix test_that_product_versions_are_ordered_correctly -- it's currently erroneously reporting (on both prod [1] and staging [2]) that " AssertionError: 32.0b is not before 32.0."

However, the site + screenshot attest otherwise.

@m8ttyB + @AndreiH + @lonnen halp?  :-)

<img src="http://i.imgur.com/3YEazXh.png">screenshot</img>

[1] http://selenium.qa.mtv2.mozilla.com:8080/view/Socorro/job/socorro.prod.saucelabs/1421/testReport/tests.test_layout/TestLayout/test_that_product_versions_are_ordered_correctly/
[2] http://selenium.qa.mtv2.mozilla.com:8080/view/Socorro/job/socorro.stage.saucelabs/1526/testReport/tests.test_layout/TestLayout/test_that_product_versions_are_ordered_correctly/

**Comment by m8ttyB** [comment]
Hey @davehunt .. interested in snagging this?

**Comment by bobsilverberg** [comment]
I am working on this.

**Comment by m8ttyB** [comment]
Thanks @bobsilverberg ! Much appreciated. This lgtm, though let's wait until [Bug 1068057](https://bugzilla.mozilla.org/show_bug.cgi?id=1068057) is resolved to make sure this is the final sort order the team wants the app to support.

**Comment by rbillings** [comment]
The [Bug 1068057](https://bugzilla.mozilla.org/show_bug.cgi?id=1068057) is still in New status, and is not being worked on.

**Comment by davehunt** [comment]
@m8ttyB is going to close this and the associated bug as WONTFIX
