### ISSUE TITLE
Bug 1086721 has been resolved -- remove xfails

### ISSUE THREAD

**Issue by m8ttyB** [mozilla/Socorro-Tests#277]
<a href="https://bugzilla.mozilla.org/show_bug.cgi?id=1086721">Bug 1086721</a> has been resolved. There are several tests that were effected; investigate if the `xfails` should be removed. If not file new bugs that explicitly reproduce the failure using manual steps -- do not simple say "automation is failing". If the tests needs to remain `xfailed`, update the `xfail` comment to point to the correct bug #.

Verify tests pass on:
* crash-stats.allizom.org
* crash-stats.mozilla.com

If tests continue to fail:
* file new bugs with manual steps that reproduce the failure
* update existing `xfails` with the newly filed bug #s

**Note:** file new bugs using <a href="https://bugzilla.mozilla.org/enter_bug.cgi?product=Socorro&component=General">this link</a>.

**Comment by stephendonner** [comment]
How's this going?

**Comment by m8ttyB** [comment]
Assigning this to me

**Comment by m8ttyB** [comment]
With the removal of the advanced search tests there are no longer any `xpasses` -- I believe we can close this.

Ancillary to this discussion I found unused pytest markers -- pr coming soon
