### ISSUE TITLE
Investigate/fix test_search_change_facet

### ISSUE THREAD

**Issue by stephendonner** [mozilla/Socorro-Tests#295]
test_search_change_facet is failing:

* http://selenium.qa.mtv2.mozilla.com:8080/job/socorro.prod.saucelabs/1844/testReport/junit/tests.test_search/TestSearchForIdOrSignature/test_search_change_facet/
* http://selenium.qa.mtv2.mozilla.com:8080/view/Socorro/job/socorro.prod/1748/testReport/junit/tests.test_search/TestSearchForIdOrSignature/test_search_change_facet/

Here's the stack:

18:38:47 =================================== FAILURES ===================================
18:38:47 _____________ TestSearchForIdOrSignature.test_search_change_facet ______________
18:38:47 [gw0] darwin -- Python 2.7.5 /Users/Shared/Jenkins/Home/jobs/socorro.prod/workspace/.env/bin/python
18:38:47 self = <tests.test_search.TestSearchForIdOrSignature instance at 0x10fb6d098>
18:38:47 mozwebqa = <pytest_mozwebqa.pytest_mozwebqa.TestSetup instance at 0x10e94bb00>
18:38:47 
18:38:47     @pytest.mark.nondestructive
18:38:47     def test_search_change_facet(self, mozwebqa):
18:38:47         csp = CrashStatsHomePage(mozwebqa)
18:38:47         cs_super = csp.header.click_super_search()
18:38:47         cs_super.select_field('product')
18:38:47         cs_super.select_operator('has terms')
18:38:47         cs_super.click_search()
18:38:47         Assert.true(cs_super.facet in cs_super.results_facet.lower())
18:38:47     
18:38:47         cs_super.click_more_options()
18:38:47         cs_super.delete_facet()
18:38:47         cs_super.type_facet('address')
18:38:47         Assert.equal(cs_super.facet, 'address')
18:38:47     
18:38:47         cs_super.click_search()
18:38:47 >       Assert.true(cs_super.facet in cs_super.results_facet.lower())
18:38:47 
18:38:47 tests/test_search.py:123: 
18:38:47 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
18:38:47 
18:38:47 self = <class 'unittestzero.Assert'>, first = False, msg = None
18:38:47 
18:38:47     @classmethod
18:38:47     def true(self, first, msg=None):
18:38:47         """
18:38:47             Asserts that what is given is equal to True
18:38:47     
18:38:47             :Args:
18:38:47              - First object to be tested
18:38:47              - Message that will be printed if it fails
18:38:47             """
18:38:47     
18:38:47 >       assert bool(first) is True, msg
18:38:47 E       AssertionError: None
18:38:47 
18:38:47 .env/lib/python2.7/site-packages/unittestzero.py:79: AssertionError
18:38:47 ------------------------------- pytest-mozwebqa --------------------------------
18:38:47 Failing URL: https://crash-stats.mozilla.com/search/?product=Firefox&_facets=address&_columns=date&_columns=signature&_columns=product&_columns=version&_columns=build_id&_columns=platform#facet-signature

**Comment by m8ttyB** [comment]
Note: This is a test that fails intermittently

**Comment by bobsilverberg** [comment]
I think I figured out what the issue was when reviewing PR #296, so I might as well take a crack at fixing this.

**Comment by stephendonner** [comment]
<3

**Comment by bobsilverberg** [comment]
This has been fixed.
