### ISSUE TITLE
Search automation failure: select version doesn't show other versions

### ISSUE THREAD

**Issue by rbillings** [mozilla/Socorro-Tests#306]
Automation is currently failing. Run 81 has few details, but https://webqa-ci.mozilla.com/job/socorro.prod/80/artifact/results.xml displays a time out issue. No recent changes have been made.

tests/test_search.py:82: in test_selecting_one_version_doesnt_show_other_versions 
Assert.equal(report.product, product) .env/lib/python2.7/site-packages/unittestzero.py:55: in equal > assert first == second, msg E AssertionError: None

**Comment by bobsilverberg** [comment]
Thanks for opening this issue, @rbillings. For future reference, the link you provided to the results.xml file is, imo, less readable than the html report, which can be found at https://webqa-ci.mozilla.com/job/socorro.prod/80/HTML_Report/. I generally link to the html report in bugs/issues/PRs.

**Comment by m8ttyB** [comment]
Thanks @rbillings -- this is a known issue, one that @bobsilverberg has a pr in for -- issue #304
