### ISSUE TITLE
Top crasher report automation failure

### ISSUE THREAD

**Issue by rbillings** [mozilla/Socorro-Tests#307]
Please investigate this test failure, time out issue.

https://webqa-ci.mozilla.com/job/socorro.prod/80/testReport/junit/tests.test_crash_reports/TestCrashReports/test_top_crasher_reports_tab_has_uuid_report/

Stacktrace

tests/test_crash_reports.py:117: in test_top_crasher_reports_tab_has_uuid_report
>       crash_signature.click_reports_tab()
pages/crash_report_page.py:30: in click_reports_tab
>       WebDriverWait(self.selenium, self.timeout).until(lambda s: not self.is_element_visible(None, *self._reports_loading_locator))
.env/lib/python2.7/site-packages/selenium/webdriver/support/wait.py:75: in until
>       raise TimeoutException(message, screen, stacktrace)
E       TimeoutException: Message:

**Comment by rbillings** [comment]
https://webqa-ci.mozilla.com/job/socorro.prod/80/HTML_Report/

**Comment by m8ttyB** [comment]
Closing .. performance tweaks have landed on production that appear to remedy this :)
