### ISSUE TITLE
Remove tests in TestLayout suite

### ISSUE THREAD

**Issue by rbillings** [mozilla/Socorro-Tests#309]
Delete the TestLayout suite needs to be removed, as it will be covered by a unit test here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1068057

* Remove tests in: TestLayout - https://github.com/mozilla/Socorro-Tests/blob/master/tests/test_layout.py#L13
** delete `test_that_product_current_versions_are_ordered_correctly`
** delete `test_that_product_older_versions_are_ordered_correctly`

* Remove all associated page object code

This is a good task for new contributors.

**Comment by m8ttyB** [comment]
@tccharles would like to take a crack at this?

**Comment by tccharles** [comment]
You bet! I'll take a look.

**Comment by rbillings** [comment]
Thanks @tccharles !
