### ISSUE TITLE
Add a setup.cfg file to configure the behaviour of flake8

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/Socorro-Tests#321]
This is a simple task: 

1. Add a new file to the repo called `setup.cfg`. The file should look just like the file found at https://github.com/mozilla/mcom-tests/blob/master/setup.cfg
2. Update the `.travis.yml` file so the `script:` line reads:
```yml
script: "flake8 ."
```

**Comment by IamAdiSri** [comment]
@bobsilverberg Hey, I think this issue has already been resolved. Both the files already have been edited.

**Comment by davehunt** [comment]
Sorry @IamAdiSri it was done here: https://github.com/mozilla/Socorro-Tests/commit/35d55444b207b8785304a8584ed0958d8b0dd732
