### ISSUE TITLE
Remove Top Changer tests

### ISSUE THREAD

**Issue by m8ttyB** [mozilla/Socorro-Tests#333]
Once <a href='https://bugzilla.mozilla.org/show_bug.cgi?id=1185055'>bug 1185055</a> lands on prod we can delete two tests:
in `tests/test_crash_reports.py`:
* line 87 `test_that_top_changers_is_highlighted_when_chosen`
* line 97 `test_that_top_changers_data_is_available`

**Comment by davehunt** [comment]
This has been fixed. Can we try to include the 'Fixes #333' mention in the comment or remember to close the comments after fixes land?
