### ISSUE TITLE
Xfail tests if bug 1222523 is not fixed

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/Socorro-Tests#335]
This is a place marker issue to act as a reminder if the tests keep failing for a few days.

I filed Bug 1222523 - "Links to SeaMonkey 2.38b1 should not be presented" [1] because of two failing tests [2]:

-  test_that_top_crashers_reports_links_work[SeaMonkey]
-  test_the_product_releases_return_results[SeaMonkey]

If these continue to fail into next week we should xfail them. If they start to pass because the bug is fixed we can close this issue.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1222523
[2] https://webqa-ci.mozilla.com/view/Buildmaster/job/socorro.prod/535/HTML_Report/

**Comment by davehunt** [comment]
Just a note that we should only xfail the parameters that are causing test failures. See http://pytest.org/latest/skipping.html#skip-xfail-with-parametrize for documentation.

**Comment by bobsilverberg** [comment]
The bug was fixed, the tests are no longer failing, we can close this. :)
