### ISSUE TITLE
Review test case for test_that_top_crasher_filter_plugin_return_results to avoid failing when no results found for past 7 days

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/Socorro-Tests#336]
`test_that_top_crasher_filter_plugin_return_results` is failing on staging [1] because there is no data found for plugins. I spoke to @peterbe and he said it is not surprising that there may not be enough data if we're only looking back 7 days. He suggested that if we change the test to look at the past 14 days instead we are less likely to experience this failure. Another suggestion was to take the second Top Crashes link (which is currently `43.0a2`), rather than the first (which is currently `44.0a1`).

@m8ttyB Which approach, if any, do you think makes sense? It sounds like we should do something, but I'm not sure what that should be. 

[1] https://webqa-ci.mozilla.com/view/Socorro/job/socorro.stage/587/HTML_Report/

**Comment by bobsilverberg** [comment]
It turns out this may actually have been caused by a bug on staging which @peterbe is going to manually fix. If the test starts passing again we can close this issue.

**Comment by peterbe** [comment]
Even the manual tool doesn't work at the moment. I filed a bug for myself on that. 
I think I ought to work on a more automated version.

**Comment by davehunt** [comment]
@m8ttyB is going to check if this is still an issue.

**Comment by m8ttyB** [comment]
The test is legitimately passing at this time. Closing this issue.
