### ISSUE TITLE
Migrate Socorro-Tests to pytest-selenium

### ISSUE THREAD

**Issue by m8ttyB** [mozilla/Socorro-Tests#337]
The time is now. Let's knock this out and celebrate the coming of 2016 with glitter and good pomp.

**Comment by davehunt** [comment]
Increasing the priority as this is the last project to migrate and I'd like to officially discontinue pytest-mozwebqa support. I also notice that @m8ttyB is no longer assigned, so I'm going to mark this as a suitable Outreachy application contribution.

**Comment by davehunt** [comment]
Here's a recent project migration that may be useful as a reference: https://github.com/mozilla/moztrap-tests/commit/d0a83f84f6765fc221ea8809c0e1a6f71c0613cd
