### ISSUE TITLE
remove xfail for bug 1228969

### ISSUE THREAD

**Issue by m8ttyB** [mozilla/Socorro-Tests#350]
[Bug 1228969](https://bugzilla.mozilla.org/show_bug.cgi?id=1228969) has been resolved and the patch has landed on production. Both stage and prod jobs show the tests xpassing. Let's remove the xfails on
  
    test_that_current_version_selected_in_top_crashers_header

**Comment by davehunt** [comment]
Fixed in https://github.com/mozilla/Socorro-Tests/commit/ccfa8318531339a5805edfc404f22ff4836a5080
