### ISSUE TITLE
Investigate test_selecting_one_version_doesnt_show_other_versions

### ISSUE THREAD

**Issue by stephendonner** [mozilla/Socorro-Tests#363]
test_selecting_one_version_doesnt_show_other_versions is failing now on staging (but passes on production):

https://webqa-ci.mozilla.com/view/Socorro/job/socorro.stage.saucelabs/908/testReport/junit/tests.test_search/TestSearchForSpecificResults/test_selecting_one_version_doesnt_show_other_versions/

Here's a local run:

`(socorro-tests) sdonners-MacBook-Pro:Socorro-Tests sdonner$ py.test --driver=Firefox -k test_selecting_one_version_doesnt_show_other_versions 

============================= test session starts ==============================
platform darwin -- Python 2.7.11, pytest-2.9.0, py-1.4.31, pluggy-0.3.1
rootdir: /Users/sdonner/Socorro-Tests, inifile: 
plugins: mozwebqa-1.6
collected 45 items 

tests/test_search.py F

=================================== FAILURES ===================================
 TestSearchForSpecificResults.test_selecting_one_version_doesnt_show_other_versions 

self = <tests.test_search.TestSearchForSpecificResults instance at 0x10427bea8>
mozwebqa = <pytest_mozwebqa.pytest_mozwebqa.TestSetup instance at 0x104277dd0>

    @pytest.mark.nondestructive
    def test_selecting_one_version_doesnt_show_other_versions(self, mozwebqa):
        maximum_checks = 20  # limits the number of reports to check
        csp = CrashStatsHomePage(mozwebqa)
        product = csp.header.current_product
        versions = csp.header.current_versions
        version = str(versions[1])
        csp.header.select_version(version)
        report_list = csp.click_last_product_top_crashers_link()
        crash_report_page = report_list.click_first_signature()
        crash_report_page.click_reports_tab()
        reports = crash_report_page.reports
    
        assert len(reports) > 0, 'reports not found for signature'
    
        random_indexes = csp.get_random_indexes(reports, maximum_checks)
        for index in random_indexes:
            report = reports[index]
>           assert product == report.product
E           assert 'Firefox' == 'Thunderbird'
E             - Firefox
E             + Thunderbird

tests/test_search.py:78: AssertionError`

**Comment by m8ttyB** [comment]
Pull #369 resolves this :)
