### ISSUE TITLE
Update Socorro-Tests to use tox

### ISSUE THREAD

**Issue by m8ttyB** [mozilla/Socorro-Tests#406]
Update the tests to use [Tox](http://tox.readthedocs.io/en/latest/). An example of a similar suite migrating to Tox can be found [here](https://github.com/mozilla/fxapom/commit/d89bd5fbc9353e4f4c0ab5d1427eab1ad1865a7e).

**Comment by stephendonner** [comment]
@m8ttyB I'd be happy to take this, but don't want to steal this from you or others, so just let me know your thoughts - cheers.

**Comment by stephendonner** [comment]
Re-ping @m8ttyB?

**Comment by m8ttyB** [comment]
@stephendonner oops .. many apologies for living this thread hanging. I meant to respond but forgot to. I think it best that we close this issue out on this repository and reopen it in https://github.com/mozilla/socorro/ to include the dev team in the discussion.

**Comment by stephendonner** [comment]
@m8ttyB makes perfect sense, given the repo/workflow move, yep!
